Add Wifi 802.11 physical simulation
veeresht/CommPy pull request #81
Opened 2020-08-20 10:45 UTC by eSoares

This adds the following changes:
 - Adds an helper class that wraps the basics of an 802.11 simulation channel (the generator matrix according to the standard, coding and puncturing when needed, depuncturing and decoding);
 - Adds the collection of more parameters of the simulation;
 - Add chunk aggregation possibility. This looks like it is the same as sending a bigger chunk, but for accounting number of some parameters it makes a difference (i.e. number of chunk loss);
 - [Breaking change] Changes from number of bits to simulate sending, to number of runs to simulate. The parameter always had that meaning and in the end I think it makes more sense. For a quick migration path, any user is advice to simple divide the number number of bits to simulate by the send chunk (and perform a rounding/ceiling);

This last change can be reverted, but makes some code of collecting more metrics a bit worse.

2020-08-20 16:04 UTC, BastienTr requested changes
Thanks for this PR @eSoares :+1:.

**WiFi 802.11**
I'm impressed by your work with WiFi, this would be a great feature! `wifi80211.py` lacks of documentation, at least on the methode callable by the user (`__init__`, `link_performance`). I'm not sure if the getter methodes should be callable by user (`get_treillis`) or specified as private (`_get_treillis`). If they are supposed to be called by user, a documentation is also required for them.

**link_performance**
You're doing a lot of changes on `link_performance`. Some of them are breacking retro-compatibility. I'm not sure to understand the point of all these changes but it seems to be to compute several metrics at once (BER + frame error). Am I right? If so, I see three solutions to prevent to lose the retrocompatibility. Your modification would prevent old my old simulation to run as expected and this must be the case for other users.

- Add your function as a new one and don't touch this one.
- Set a warning in the next realease and merge these changes in master only when the warnng had been released. This could be merged with the previous solution: add the function as a new one and warn that `link_performance` will be changed to match the new one.
- Revert the change to keep the compatibility.

This is just my point of view and I'm not sure on this one. @eSoares and @veeresht, feel free to give yours.

2020-08-20 16:11 UTC, BastienTr commented
We will also think about updating the readme and documentation build after these additions. I can handle this once the code has been stabilized.

2020-08-24 11:20 UTC, eSoares commented on THANKS.txt
> +@eSoare for several enhancements including WiFi 802.11 class and code speedups.
Added my name and typo fix. No problem :)

2020-08-24 11:20 UTC, eSoares commented on commpy/wifi80211.py
> +              A list of MCS and which coding and modulations they correspond to
Done :)

2020-08-24 13:20 UTC, BastienTr commented
Great! Thanks again for this new features. It must be the most important additions for v0.6 by someone that is not a official collaborator. :+1:

2020-08-24 13:20 UTC, merged